### ISSUE TITLE
Area code is not set installing data for module

### ISSUE THREAD

**Issue by craigcarnell** [bazaarvoice/magento2-extension#1]
Magento 2.1.5 EE

```
Module 'Bazaarvoice_Connector':
Installing data... 
 
                                                    
  [Magento\Framework\Exception\LocalizedException]  
  Area code is not set  
```

The issue appears to be in Setup/InstallData.php
 
// @codingStandardsIgnoreEnd

 
Perhaps the solution might be:
 
```
try {
            if (!$this->_state->getAreaCode()) {
    $this->_state->setAreaCode('frontend');
}
 
        } catch (\Exception $ex) {
            $output->writeln("Areacode was already set");
        }
 ```

**Comment by drake1701** [comment]
What is $output in this context?

Also, if you're catching an ex trying to set the areacode, won't you still get the "area code is not set" error?

**Comment by tua** [comment]
got the same error

**Comment by tua** [comment]
anyway,   https://github.com/minhnd55/magento2-extension/commit/d017c8f95f6772d271c3a75cb36964008231292e works.

**Comment by craigcarnell** [comment]
@drake1701 I'm not catching anything, it was just a suggestion

**Comment by drake1701** [comment]
Alright, it sounds like the issue is resolved then?

**Comment by craigcarnell** [comment]
@drake1701 I'll let you know when you tag a new release :)

**Comment by craigcarnell** [comment]
Can this issue be reopened?

**Comment by drake1701** [comment]
I think I see what's happening, at least with the conditionals. Are you still on 2.1.5 EE?

**Comment by craigcarnell** [comment]
@drake1701 Yes it is a clean install of Magento EE 2.1.5

**Comment by drake1701** [comment]
Alright we're still unable to test on our end, so I'm attaching an updated InstallData.php to see if that fixes it.
[InstallData.php.zip](https://github.com/bazaarvoice/magento2-extension/files/879405/InstallData.php.zip)

**Comment by craigcarnell** [comment]
@drake1701 

```
Module 'Bazaarvoice_Connector':
Installing data... 
```

It crashes without an error message

**Comment by drake1701** [comment]
Alright, I'm going to do some digging on our end and see if we can reproduce it.  Can you try running `bin/magento setup:upgrade -vvv` and see if the verbose flag gives any more info?

**Comment by drake1701** [comment]
@craigcarnell sorry for the delay on this. It's still installing fine on our servers. Could you possibly walk us through the steps you're using to install?
