### ISSUE TITLE
Enable BV Product Families option does not seem to work

### ISSUE THREAD

**Issue by tonybluebadger** [bazaarvoice/magento2-extension#11]
If you look at app/code/Bazaarvoice/Connector/Model/Feed/Product/Product.php:164, there is a condition which checks if feeds/families is enabled. 

The 'families' node is located under the 'general' node, causing that condition to never evaluate to true.

Thank you.

**Comment by chrismshea** [comment]
We'll include a fix for this in the next release.  I don't currently know when that will be.

**Comment by chrismshea** [comment]
Resolved in 7.0.11
