### ISSUE TITLE
Broken JS url when locale not set.

### ISSUE THREAD

**Issue by davidangel** [bazaarvoice/magento2-extension#15]
If the locale is left `null`, then the url to the JS file ends up containing two slashes `//`, and fails to load correctly (tested in Chrome/Mac).

I've opened [this PR](https://github.com/bazaarvoice/magento2-extension/pull/12) to address the issue.

**Comment by chrismshea** [comment]
Hi David,

I brought up this issue internally, and while the url for bvapi.js will work without locale the next release of the extension will use the new loader at bv.js which will require the locale to be included when forming the url.  Also, I believe that even in the case where you don't have a locale it still defaults to en_US.
