### ISSUE TITLE
SFTP seclib constants are incorrect in Magento 2.1.x

### ISSUE THREAD

**Issue by bangerkuwranger** [bazaarvoice/magento2-extension#17]
At some point, Magento introduced a bug in their framework by updating seclib but not updating the SFTP IO framework to use the new constants. This issue was resolved by [PR 6](https://github.com/bazaarvoice/magento2-extension/pull/6), but was closed prematurely because the authors muddled up some other code style / local issue fixes in the PR. We've run into the same issue, namely that SFTP fails with an undefined constants exception before uploading the file. This occurs on Magento ee/commerce v 2.1.9, and is not slated for a core fix in the magento 2.1.x branch... I've added the fix in [pull request #16](https://github.com/bazaarvoice/magento2-extension/pull/16), and it would be helpful if this could be merged so we can deploy the fix via composer. Thanks!!

**Comment by bangerkuwranger** [comment]
Changes suggested by @nntoan are more elegant than the original solution... either way, would be good to get this issue addressed so sftp upload of feed files will work w/ versions of Magento affected by the seclib oversight. Thanks!!

**Comment by chrismshea** [comment]
Implemented in 7.1.0
