### ISSUE TITLE
Command class "Bazaarvoice\Connector\Console\Command\Export" is not correctly initialized

### ISSUE THREAD

**Issue by craigcarnell** [bazaarvoice/magento2-extension#24]
bin/magento setup:upgrade with latest release..

```                                                                                                     
  [Symfony\Component\Console\Exception\LogicException]                                                                                            
  Command class "Bazaarvoice\Connector\Console\Command\Export" is not correctly initialized. You probably forgot to call the parent constructor.
```

**Comment by parthaccorin** [comment]
I am getting the same error.

It should be `$this->_exporter = $exporter;` in Bazaarvoice\Connector\Console\Command\Export as it does not match with the variable defined.

also, it extends `Symfony\Component\Console\Command\Command;` and parent constructor is not defined here.

which gives an error on setup: upgrade as below
`[Symfony\Component\Console\Exception\LogicException]                                                                                            
  Command class "Bazaarvoice\Connector\Console\Command\Export" is not correctly initialized. You probably forgot to call the parent constructor.`

**Comment by Zaedred** [comment]
Also getting this same error. Is there a fix or work around?

**Comment by drake1701** [comment]
What Magento version?

**Comment by Zaedred** [comment]
@drake1701 I'm using Magento 2.2.3

**Comment by chrismshea** [comment]
Interesting.  This did not happen for us in setup:upgrade only when running that command, and not on all versions.  7.1.4.2 is out to address this issue.
