### ISSUE TITLE
https issue and Deployment Zone

### ISSUE THREAD

**Issue by tua** [bazaarvoice/magento2-extension#3]
if there is a /admin/system_config/edit/section/web/Offloader header for https instead of $_SERVER['HTTPS'], the url will not work.

And i'm not quite sure if Deployment Zone is required. I do not have it for now, so from my testing, when i change below code:
$url = $protocol . '://' . $apiHostname . '/' . $static . $clientName . '/' . urlencode($deploymentZoneName) . '/' . $localeCode;  

To:

$url = $protocol . '://' . $apiHostname . '/' . $static . $clientName . '/' . $localeCode;

The url works.   I have to change it because there is a "/" after urlencode($deploymentZoneName).

**Comment by tua** [comment]
btw, use Offloader header instead of $_SERVER['HTTPS'] because the server is behind load balancer.

**Comment by drake1701** [comment]
So this issue is the double slash if deployment zone is null?  That should probably be checked in another line and the slash added there if present. Obviously we can't just leave it out of the URL. Would you like us to update the module?

**Comment by tua** [comment]
I got the Deployment Zone now and update in the backend. RIght now the url works, ignore double slash issue, i guess it's a required field. It's ok.
Please resolve the HTTPS issue. It cannot work behind a load balancer

**Comment by drake1701** [comment]
Unfortunately I'm not very familiar with this load balancer issue. Would it be sufficient to remove the protocol from the bvapi url like `src="//display-stg.ugc.bazaarvoice.com/...`?

**Comment by tua** [comment]
Yes, //display-stg.ugc.bazaarvoice.com/... can works. Or you can update Bazaarvoice\Connector\Helper\Data like this :

From:
$protocol = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != '') ? 'https' : 'http';

To:
$protocol = $this->_request->isSecure() ? 'https' : 'http';

**Comment by chrismshea** [comment]
We have included this work in the latest release-706 branch, and will update master, and release version 7.0.6 this week.  Closing issue.
