### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getId() 

### ISSUE THREAD

**Issue by sashas777** [bazaarvoice/magento2-extension#30]
Release 7.1.6
After deploy Magento shows exception:

 
Fatal error: Uncaught Error: Call to a member function getId() on null in vendor/bazaarvoice/bazaarvoice-magento2-ext/Block/Product.php:118 Stack trace:
 #0 vendor/bazaarvoice/bazaarvoice-magento2-ext/Block/Product.php(184): Bazaarvoice\Connector\Block\Product->getProduct()
 #1 vendor/magento/framework/View/Element/AbstractBlock.php(667): Bazaarvoice\Connector\Block\Product->_toHtml()
 #2 vendor/magento/framework/View/Layout.php(558): Magento\Framework\View\Element\AbstractBlock->toHtml()
 #3 vendor/magento/framework/View/Layout.php(534): Magento\Framework\View\Layout->_renderBlock('bazaarvoice.hea...')
 #4 vendor/magento/framework/View/Layout.php(489): Magento\Framework\View\Layout->renderNonCachedElement('bazaarvoice.hea...')
 #5 vendor/magento/framework/View/Layout.php(585): Magento\Framework\View\Layout->renderElement('bazaarvoice.hea...')
 #6 vendor/magento/framework/View/Layout.php(536): Magento\Framework\View\Layout->_renderContainer('after.body.star...')
 #7 vendor/magento/fram in vendor/bazaarvoice/bazaarvoice-magento2-ext/Block/Product.php on line 118

**Comment by sashas777** [comment]
@hrismshea Please check this issue. 
Seems that when it is not at the product page the code 
`$product        = $this->_coreRegistry->registry( 'product' );`
doesn't work what cause the issue.

**Comment by chrismshea** [comment]
Reviewing

**Comment by craigcarnell** [comment]
@chrismshea can confirm this bug

**Comment by baublet** [comment]
Can confirm. The fix is simple: /vendor/bazaarvoice/bazaarvoice-magento2-ext/Block/Product.php

![screen shot 2018-06-11 at 6 18 25 pm](https://user-images.githubusercontent.com/3482661/41260048-dab33d34-6da3-11e8-8034-407baf4f186b.png)

Just needs to be made downstream.
