### ISSUE TITLE
When module removed it doesnt remove created attributes

### ISSUE THREAD

**Issue by sashas777** [bazaarvoice/magento2-extension#31]
When module removed using  composer remove and bin/magento module:uninstall it doesn't removes attributes.

It needs Setup/Uninstall.php file. Please refer to the article: http://inchoo.net/magento-2/setup-scripts-magento-2/

Thank you for your help!

**Comment by sashas777** [comment]
@chrismshea Thank you for your help!

**Comment by acashley** [comment]
I want to second this issue. This module breaks my whole M2 site when uninstalled via composer.
It leaves behind product attributes, BV database tables and BV modifications to other product-related database tables. 

Please include a proper Uninstall.php file as @sashas777 requested.

PS: @chrismshea - I don't see anything in the referenced commit https://github.com/bazaarvoice/magento2-extension/commit/e67d3eab3965e145acf2e496662f404b3938b67e that has to do with this issue?

**Comment by jantzenw** [comment]
Hi,

v9.0.0 of the extension has been released today that removes Bazaarvoice-created tables and product and order attributes. Please try that version and let us know if you encounter any issues.
