### ISSUE TITLE
Getting error on search page on magento 2.2.5

### ISSUE THREAD

**Issue by parthaccorin** [bazaarvoice/magento2-extension#33]
Getting below error on search page on Magento 2.2.5

`Exception #0 (RuntimeException): Source class "\Magento\CatalogSearch\Block\SearchResult\ListProduct" for "Magento\CatalogSearch\Block\SearchResult\ListProduct\Interceptor" generation does not exist.`

it's being solved if I make changes on the di.xml file for `Magento\CatalogSearch\Block\SearchResult\ListProduct`

if I change it to virtualType in place of the type it's working fine and it's currently breaking our site, can you please release that fix?

PR is here > https://github.com/bazaarvoice/magento2-extension/pull/34

**Comment by chrismshea** [comment]
Including this in 7.1.8 which will be released next week.

**Comment by chrismshea** [comment]
You can update to 7.1.8 which has been released.  There were other issues with 2.2.5 in addition to search results.
