### ISSUE TITLE
Error on page load

### ISSUE THREAD

**Issue by kinexvikas** [bazaarvoice/magento2-extension#35]
Hi there,

I have installed BV extn in magento cloud ver 2.2.5 and configured as per BV knowledge base document. Facing below error on page load. 

SyntaxError: expected expression, got '<'[Learn More] bvapi.js:1
ReferenceError: $BV is not defined[Learn More] test-sony-75-inch-led-4k-ultra-hd-with-android-os-xbr75x850f.html:257:9
ReferenceError: $BV is not defined[Learn More] test-sony-75-inch-led-4k-ultra-hd-with-android-os-xbr75x850f.html:855:5

Please look into this.

Thank You!
Vikas Bansal

**Comment by chrismshea** [comment]
@kinexvikas I'm going to need a bit more information in order to assist you.  Please provide the full url for bv.js found in the source of your PDP to chris.shea@bazaarvoice.com

Thanks!

**Comment by kinexvikas** [comment]
@chrismshea Thanks for your reply! Issue is resolved now. 
I have one more question. 
How to run this extension on my local system for designing purposes as we have to provide url in Bazaarvoice Workbench? 

Thanks!

**Comment by chrismshea** [comment]
Hi @kinexvikas you should direct this through the appropriate person at Bazaarvoice.  Usually there is support, and implementation teams that work with you on these types of requests.  It is outside of the Extension.  Please feel free to email with the client you are working for and I can help you get to the correct person.

**Comment by kinexvikas** [comment]
@chrismshea Alright! Thanks for your support.
