### ISSUE TITLE
JS error on some PDP's

### ISSUE THREAD

**Issue by subbu1993** [bazaarvoice/magento2-extension#36]
## Pre-requisites
Magento version - 2.2.5
BV version - 7.1.3
php - 7.0.31

## Issue
Error: A node with "data-bv-show="questions"" is required.

On some PDPs this error is being thrown. This stems from https://apps.bazaarvoice.com/apps/questions/questions-0.2.2.js. I personally have not been able to get the error to show, but would this happen when the **Ask a question** link does not show ?

**Comment by chrismshea** [comment]
Hello, thanks for contacting us.  Please create a support ticket with your Bazaarvoice representative.  This does not sound like an issue stemming from the extension.  Just a side note you will want to update to the latest for 2.2.5 support.
