### ISSUE TITLE
CLI Indexer outputs to screen

### ISSUE THREAD

**Issue by bobbrodie** [bazaarvoice/magento2-extension#37]
When we reindex from the CLI, the Bazaarvoice logs are sometimes printed to the screen, which should not happen.

**Comment by jantzenw** [comment]
Hi bobbrodie,

Sorry for the (years) delay. I was going through old issues and pull requests and found this one. The CLI indexer has since been updated to only outputs extra data to the screen when Stores > Settings > Configuration > General > Bazaarvoice Connector > General > Debug is set to Yes.
