### ISSUE TITLE
Confusing attribute name: bv_feed_exclude - means "include" - documentation would be helpful

### ISSUE THREAD

**Issue by kmddevdani** [bazaarvoice/magento2-extension#43]
It seems as if this line in `Model/Feed/ProductFeed.php` has caused quite some confusion in our case:

```
    const INCLUDE_IN_FEED_FLAG = 'bv_feed_exclude';
```

It would be quite helpful to find a hint in the documentation and the README.md file, explaining that the bazaarvoice product feed will contain only products that have a value of "1" for the attribute "bv_feed_exclude".

It might sound even more appealing to change the attribute name to `bv_feed_include`, but that might require changes for customers with customized product integration and migration. Therefore, documentation could be the way to go.

**Comment by chrismshea** [comment]
Hello, this is in the documentation. https://knowledge.bazaarvoice.com/software/downloads/PartnerIntegrations/Magento_Extension/Magento_2/Conversations/Bazaarvoice%20for%20Magento%20Extension%20v7.1.10.pdf
