### ISSUE TITLE
Extension causing bin/magento setup:upgrade to fail on Magento 2.3

### ISSUE THREAD

**Issue by craigcarnell** [bazaarvoice/magento2-extension#45]
Magento 2.3.0:
bin/magento setup:upgrade

```
Cannot process definition to array for type enum
vendor/magento/framework/Setup/Declaration/Schema/Db/DefinitionAggregator.php
line 58
(
    [name] => scope
    [default] => 
    [type] => enum
    [nullable] => 1
    [definition] => enum('global','website','group','view')
    [extra] => 
    [comment] => 
)
```

Table referenced is bazaarvoice_index_product

Presumably this line?
vendor/bazaarvoice/bazaarvoice-magento2-ext/Setup/UpgradeSchema.php

```
`scope` enum('".Scope::SCOPE_GLOBAL."','".Scope::WEBSITE."','".Scope::STORE_GROUP."','".Scope::STORE_VIEW."') NULL,
```

This code has already run before, my version is the latest.

**Comment by drake1701** [comment]
Magento support didn't seem that helpful in this. It looks like they've changed or removed the way they handle enum type columns. It's probably not necessary and could just be changed to varchar.

```
`scope` varchar(255) NULL,
```

**Comment by craigcarnell** [comment]
@chrismshea @drake1701 Are you able to update me on this issue please?

**Comment by chrismshea** [comment]
Hi @craigcarnell,

We'll be releasing 7.1.13 this upcoming week which will resolve this issue for 2.3.0.

**Comment by chrismshea** [comment]
This is released.

**Comment by drew7721** [comment]
Just did an update from 2.2.10 to 2.3.3 and it's still throwing that error. The `scope` field in the `bazaarvoice_index_product` table is still of `enum` type. I'm on version 8.1.3 of this extension so I guess none of these updates actually changed the type of the column. What do you suggest to fix this? Should the `bazaarvoice_index_product` table be deleted post upgrade?
