### ISSUE TITLE
Disable Core reviews?

### ISSUE THREAD

**Issue by jpratt** [bazaarvoice/magento2-extension#46]
This module disables core review output. Would it be better to rely on the user disabling it per store view? This is troublesome as one instance can have multiple sites. In our case, we have many sites and only a few require BV reviews. All others use the core reviews, so installing this breaks all stores that use core reviews.

**Comment by chrismshea** [comment]
Working on a resolution for that now.  Will be changed in 7.1.13 to support using native Magento Reviews on some store views and Bazaarvoice on others.

**Comment by chrismshea** [comment]
The release 7.1.13 is out.
