### ISSUE TITLE
Product feed category external_id values don't match in product and category nodes, and have invalid chars in certain cases.

### ISSUE THREAD

**Issue by bangerkuwranger** [bazaarvoice/magento2-extension#5]
Running the latest version of the module in Magento 2.1.5 EE.

Product feed scope is 'website' and 'use url path for category external id' is set to true.

Our urls are set to append '.html' to all category and product paths. This presents a couple of issues: 1st is that category nodes end up with an external_id without the '.html', and product nodes end up with a category external id that include it. Issue one is that mismatch; products end up associated with no category in BazaarVoice. Second issue is that according to our integration engineer at BV, although the period character is technically legal, and will pass XML validation, the BV parser doesn't handle it well as part of an external ID. 

We've submitted a PR that addresses the issue:
https://github.com/bazaarvoice/magento2-extension/pull/4
Thanks!!

**Comment by chrismshea** [comment]
I have just merged this into the latest release branch.  For version 7.0.6 which should be out by end of week.
