### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Bazaarvoice\Connector\Model\Feed\Status' not found in /vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Feed/PurchaseFeed.php:316

### ISSUE THREAD

**Issue by craigcarnell** [bazaarvoice/magento2-extension#54]
The class Status does not exist

Fatal error: Uncaught Error: Class 'Bazaarvoice\Connector\Model\Feed\Status' not found in /vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/Feed/PurchaseFeed.php:316

Is it  \Magento\Catalog\Model\Product\Attribute\Source\Status ?

**Comment by jantzenw** [comment]
Hi @craigcarnell,

Thank you for your report. I am very sorry for the delayed response. Yes, `\Magento\Catalog\Model\Product\Attribute\Source\Status` was the missing class. This issue has been resolved in version 7.2.5 of the extension.
