### ISSUE TITLE
trackTransaction missing wrap around function call

### ISSUE THREAD

**Issue by craigcarnell** [bazaarvoice/magento2-extension#55]
Documentation says that there should be a function around the trackTransaction call:
https://knowledge.bazaarvoice.com/wp-content/conversations/en_US/Collect/bvpixel.html#add-the-transaction-event

There is no function:
https://github.com/bazaarvoice/magento2-extension/blob/master/view/frontend/templates/checkout/onepage/success/bvpixel.phtml

Should be:

```
        window.bvCallback = function (BV) {
            BV.pixel.trackTransaction(transactionData);
        }
```

**Comment by jantzenw** [comment]
This has been resolved in v8.0.0+ of the extension, with the latest version as of this writing being v8.1.3. Please test that the latest version of the extension resolves your issue. Thanks!
