### ISSUE TITLE
Problem with rating summary

### ISSUE THREAD

**Issue by Stevie-Ray** [bazaarvoice/magento2-extension#56]
Hello Bazaarvoice, 

We are using this module for one of our clients, and noticed the review-summary is displaying an error on the product detail page, while the review tab and inline ratings seems to work.

```
<ul id="BVSEOSDK_meta" style="display:none !important;">
   <li data-bvseo="sdk">bvseo_sdk, p_sdk, 3.2.1</li>
   <li data-bvseo="sp_mt">CLOUD, getAggregateRating, 85ms</li>
   <li data-bvseo="ct_st">REVIEWS, PRODUCT</li>
   <li data-bvseo="ms">bvseo-msg:  HTTP status code of 404 was returned;</li>
</ul>
```

_vendor/bazaarvoice/bazaarvoice-magento2-ext/view/frontend/templates/rr/summary.phtml_

```
<?php /** @var \Bazaarvoice\Connector\Block\Reviews $this */ ?>
<?php if ($this->isEnabled()) : ?>
    <div data-bv-show="rating_summary"
         data-bv-product-id="<?php echo $this->getProductSku() ?>">
        <?php echo $this->getAggregateSEOContent() ?>
    </div>
<?php endif;
```

if we change _rating_summary_ to _inline_rating_ or _reviews_ we get results. I'm not sure if this is a bug or our environment is wrongly configured. Thanks for your help.

Stevie

**Comment by XjSv** [comment]
I am getting the same error, and just like you, it is only happening on the product detail page.

![Image 001](https://user-images.githubusercontent.com/107681/59213277-7bc49180-8b82-11e9-81dc-62c5e5f17cc7.png)

**Comment by carlos-reynosa** [comment]
This may be related to #73
