### ISSUE TITLE
Can not run reindex 

### ISSUE THREAD

**Issue by hoangvjet** [bazaarvoice/magento2-extension#62]
I cannot reindex when disable catalog flat.
Please update allow we can use when disable catalog flat.

**Comment by aepod** [comment]
Flat table must be off in Magento 2.3.0+
https://docs.magento.com/m2/ce/user_guide/catalog/catalog-flat.html
`Starting with Magento 2.3.0+, the use of a flat catalog is no longer a best practice and is not recommended. Continued use of this feature is known to cause performance degradation and other indexing issues.`

**Comment by jantzenw** [comment]
I am sorry for the delay. It is now possible to run a reindex without this extension causing an error when flat tables are disabled in v8.1.4+ of the extension. Please upgrade to v8.1.4 or higher and see that you are able to reindex without issue. 

Please note that at this time, flat tables are still required for proper functioning of the Bazaarvoice Product XML Feed feature. This change only resolves the fatal error when reindexing. 

But please note that the new Dynamic Catalog Collection (DCC) feature is an alternative to the Product XML Feed and can be used with flat tables disabled. And we now recommend using DCC over the Product XML Feed in most cases. Please see the official documentation for details on DCC: https://knowledge.bazaarvoice.com/software/downloads/PartnerIntegrations/Magento_Extension/Magento_2/Conversations/Bazaarvoice%20for%20Magento%202%20Extension%20v8.1.3.pdf

**Comment by jantzenw** [comment]
Hi,

v9.0.0 of the extension has been released today that supports the product xml feed with flat tables disabled. Please try that version and let us know if you encounter any issues.
