### ISSUE TITLE
SFTP Password unencrypted

### ISSUE THREAD

**Issue by ericclaeren** [bazaarvoice/magento2-extension#70]
Hi,

The sftp_password in is not encrypted in the core config data table. Although you have a large issue when your DB is compromised, It would be a very good practice to always encrypt passwords.

You can use a backend model in system.xml
`<backend_model>Magento\Config\Model\Config\Backend\Encrypted</backend_model>`

You should also add a dataPatch to remove the current password and set a notice for site owners to enter their password again. I don't know if it's possible to update the password with encryption in the dataPatch.

Cheers

**Comment by ericclaeren** [comment]
Yes it's possible to get plain text value, encrypt it and save it to config in a DataPatch.

**Comment by ericclaeren** [comment]
Any news/response on this?

**Comment by jantzenw** [comment]
Hi,

Sorry for the delay. As of version 8.3.0+, the SFTP password is now encrypted and existing passwords will become encrypted during setup:upgrade. Please upgrade to this version and let us know if this resolves your issue.

**Comment by jantzenw** [comment]
Actually, please upgrade to 8.3.1+. Fixed a syntax error in earlier versions of PHP introduced in 8.3.0.

**Comment by jantzenw** [comment]
Actually upgrade to 8.3.2 if possible. Resolved a critical issue with the SFTP connectivity due to the new encrypted passwords not being properly decrypted.
