### ISSUE TITLE
8.3.1 - Unable to open SFTP connection

### ISSUE THREAD

**Issue by haiacom** [bazaarvoice/magento2-extension#71]
Hi,

I am using 8.3.1 and unable to upload product feed to bazaavoice via SFTP, I got this message:
"Unable to open SFTP connection as....."

The problem is the password is encrypted however it is not decrypted when getting value from DB, We need to add backend_model to config.xml for sftp_password field

Thanks.

**Comment by jantzenw** [comment]
Hi,

Sorry for this issue. Thank you for bringing it to our attention. The password is now properly decrypted in v8.3.2. Please upgrade to that version and let us know if that resolves it.

**Comment by haiacom** [comment]
HI @jantzenw 

I have just checked but couldn't see <sftp_password backend_model="Magento\Config\Model\Config\Backend\Encrypted" /> in etc/config.xml

Regards,
Hai.

**Comment by jantzenw** [comment]
It was implemented by adding decryption to the field retrieval, not by modifying etc/config.xml.

**Comment by haiacom** [comment]
thanks @jantzenw

**Comment by haiacom** [comment]
sorry just double check again, and got this error:
syntax error, unexpected 'EncryptorInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in vendor/bazaarvoice/bazaarvoice-magento2-ext/Model/ConfigProvider.php on line 44"

**Comment by jantzenw** [comment]
Sorry for that. Incompatibility with earlier versions of PHP. Please upgrade to 8.3.3 released just now and try again.

**Comment by haiacom** [comment]
thanks @jantzenw
