### ISSUE TITLE
Magento 2.4.x  with flat tables disabled

### ISSUE THREAD

**Issue by Abdallah-herri** [bazaarvoice/magento2-extension#75]
Hi,

Since version 2.1.x Magento discourage using flat tables
https://docs.magento.com/m2/ce/user_guide/catalog/catalog-flat.html

Knowing that, and from what i understood, product feed implemented in the module need flat tables to be enabled.
Is it mandatory to use DCC, or is there any way to use product feed with fkat tab les being disabled.

Kind regards, 
Abdallah

**Comment by jantzenw** [comment]
Hi,

v9.0.0 of the extension has been released today that supports the product xml feed with flat tables disabled. Please try that version and let us know if you encounter any issues.
